version: "3.8"

services:
  app:
    build: .
    command: bash start.sh
    ports:
      - "5005:5005"
    environment:
      - GRADLE_USER_HOME=/box
    volumes:
      - .:/algaworks-ecommerce
      - box:/box
    depends_on:
      - db
  db:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=algaworks_ecommerce
    ports:
      - "3306:3306"
  box:
    image: busybox
    volumes:
      - /box

volumes:
  db:
  box: