version: "3.8"

services:
  app:
    build: .
    command: bash start.sh
    ports:
      - "5005:5005"
    environment:
      - GRADLE_USER_HOME=/box
    volumes:
      - .:/algaworks-ecommerce
      - box:/box
    depends_on:
      - db
      - db2
  db:
    image: mysql:8.0.26
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=algaworks_ecommerce
    ports:
      - "3306:3306"
  db2:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=algaworks_ecommerce
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  box:
    image: busybox
    volumes:
      - /box

volumes:
  db:
  box:
  db2: